/**
 * services/trip.service.ts
 *
 * Business logic for Trip management.
 * This layer is the ONLY place that talks to the Trip model.
 * Controllers call these methods; this file never touches req/res.
 *
 * Methods:
 *  - createTrip       → validates uniqueness concerns, sets status = Draft
 *  - getAllTrips       → list with optional status filter + pagination
 *  - getTripById      → find one or throw 404
 *  - updateTrip       → partial update (Draft trips only for core fields)
 *  - deleteTrip       → hard delete (Draft/Cancelled only)
 */

import mongoose from 'mongoose';
import Trip    from '../models/Trip.model';
import Vehicle from '../models/Vehicle.model';
import Driver  from '../models/Driver.model';
import { ApiError }      from '../utils/ApiError';
import { TripStatus, VehicleStatus, DriverStatus } from '../constants/enums';
import { CreateTripInput } from '../validators/trip.validator';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface TripListQuery {
  status?:  TripStatus;
  page?:    number;
  limit?:   number;
}

export interface UpdateTripPayload {
  source?:          string;
  destination?:     string;
  vehicleId?:       string;
  driverId?:        string;
  cargoWeight?:     number;
  plannedDistance?: number;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Assert a string is a valid Mongo ObjectId; throw 400 if not. */
function assertObjectId(value: string, fieldName: string): void {
  if (!mongoose.Types.ObjectId.isValid(value)) {
    throw new ApiError(400, `Invalid ${fieldName}`);
  }
}

// ── Pre-trip Creation Guard ───────────────────────────────────────────────────

/**
 * Runs all vehicle + driver eligibility checks in parallel before a trip
 * is created. Throws a descriptive ApiError on the first failed rule.
 *
 * Checks performed:
 *  Vehicle:
 *    1. Vehicle exists in the database
 *    2. Vehicle is not Retired
 *    3. Vehicle is not In Shop
 *    4. Vehicle status is Available
 *
 *  Driver:
 *    5. Driver exists in the database
 *    6. Driver is not Suspended
 *    7. Driver license is not expired (licenseExpiry > now)
 *    8. Driver status is Available
 */
async function validateTripPreConditions(
  vehicleId:   string,
  driverId:    string,
  cargoWeight: number,
): Promise<void> {
  // Fetch both in parallel — one round-trip to the DB
  const [vehicle, driver] = await Promise.all([
    Vehicle.findById(vehicleId).select('status plateNumber capacity').lean(),
    Driver.findById(driverId).select('status licenseExpiry name').lean(),
  ]);

  // ── Vehicle checks ────────────────────────────────────────────────────────
  if (!vehicle) {
    throw new ApiError(404, `Vehicle not found (id: ${vehicleId})`);
  }

  if (vehicle.status === VehicleStatus.RETIRED) {
    throw new ApiError(
      422,
      `Vehicle "${vehicle.plateNumber}" is Retired and cannot be assigned to a trip`,
    );
  }

  if (vehicle.status === VehicleStatus.IN_SHOP) {
    throw new ApiError(
      422,
      `Vehicle "${vehicle.plateNumber}" is currently In Shop (under maintenance) and cannot be dispatched`,
    );
  }

  if (vehicle.status !== VehicleStatus.AVAILABLE) {
    throw new ApiError(
      422,
      `Vehicle "${vehicle.plateNumber}" is not Available. Current status: ${vehicle.status}`,
    );
  }

  // ── Cargo weight vs vehicle capacity ─────────────────────────────────────
  if (cargoWeight > vehicle.capacity) {
    throw new ApiError(
      400,
      'Cargo weight exceeds vehicle capacity.',
    );
  }

  // ── Driver checks ─────────────────────────────────────────────────────────
  if (!driver) {
    throw new ApiError(404, `Driver not found (id: ${driverId})`);
  }

  if (driver.status === DriverStatus.SUSPENDED) {
    throw new ApiError(
      422,
      `Driver "${driver.name}" is Suspended and cannot be assigned to a trip`,
    );
  }

  const now = new Date();
  if (new Date(driver.licenseExpiry) <= now) {
    const expiredOn = new Date(driver.licenseExpiry).toLocaleDateString('en-IN');
    throw new ApiError(
      422,
      `Driver "${driver.name}" has an expired license (expired on ${expiredOn}). Renew the license before assigning trips`,
    );
  }

  if (driver.status !== DriverStatus.AVAILABLE) {
    throw new ApiError(
      422,
      `Driver "${driver.name}" is not Available. Current status: ${driver.status}`,
    );
  }
}

// ── Service Methods ───────────────────────────────────────────────────────────

/**
 * POST /api/trips
 * Creates a new trip with status = Draft.
 * tripNumber is auto-generated by the model's pre-validate hook.
 */
export async function createTrip(input: CreateTripInput) {
  const { vehicleId, driverId, ...rest } = input;

  assertObjectId(vehicleId, 'vehicleId');
  assertObjectId(driverId,  'driverId');

  // ── Pre-creation eligibility checks ──────────────────────────────────────
  // Validates vehicle + driver exist and are eligible before touching the
  // trips collection. Throws a descriptive 404/422 ApiError on any failure.
  await validateTripPreConditions(vehicleId, driverId, rest.cargoWeight);


  const trip = await Trip.create({
    ...rest,
    vehicle: vehicleId,
    driver:  driverId,
    status:  TripStatus.DRAFT,   // always Draft on creation — explicit, not relied on default
  });

  return trip;
}


/**
 * GET /api/trips
 * Returns a paginated list of trips.
 * Supports optional ?status=Draft|Dispatched|Completed|Cancelled filter.
 */
export async function getAllTrips(query: TripListQuery = {}) {
  const { status, page = 1, limit = 20 } = query;

  const filter: Record<string, unknown> = {};
  if (status) {
    // Validate the status value against the enum
    if (!Object.values(TripStatus).includes(status)) {
      throw new ApiError(400, `Invalid status value. Must be one of: ${Object.values(TripStatus).join(', ')}`);
    }
    filter.status = status;
  }

  const skip  = (page - 1) * limit;
  const total = await Trip.countDocuments(filter);

  const trips = await Trip.find(filter)
    .sort({ createdAt: -1 })
    .skip(skip)
    .limit(limit)
    .populate('vehicle', 'plateNumber type')
    .populate('driver',  'name licenseNumber');

  return {
    trips,
    pagination: {
      total,
      page,
      limit,
      totalPages: Math.ceil(total / limit),
    },
  };
}

/**
 * GET /api/trips/:id
 * Finds a single trip by MongoDB _id.
 * Throws 404 if not found.
 */
export async function getTripById(id: string) {
  assertObjectId(id, 'trip ID');

  const trip = await Trip.findById(id)
    .populate('vehicle', 'plateNumber type capacity')
    .populate('driver',  'name licenseNumber phone');

  if (!trip) {
    throw new ApiError(404, `Trip not found`);
  }

  return trip;
}

/**
 * PUT /api/trips/:id
 * Updates editable fields of a trip.
 *
 * Business rules:
 *  - Only Draft trips can have their core fields edited.
 *  - Dispatched / Completed / Cancelled trips are immutable via this endpoint.
 */
export async function updateTrip(id: string, payload: UpdateTripPayload) {
  assertObjectId(id, 'trip ID');

  const trip = await Trip.findById(id);
  if (!trip) throw new ApiError(404, 'Trip not found');

  if (trip.status !== TripStatus.DRAFT) {
    throw new ApiError(
      409,
      `Only Draft trips can be edited. Current status: ${trip.status}`,
    );
  }

  const { vehicleId, driverId, ...rest } = payload;

  // Validate ObjectIds if provided
  if (vehicleId) {
    assertObjectId(vehicleId, 'vehicleId');
    trip.vehicle = new mongoose.Types.ObjectId(vehicleId);
  }
  if (driverId) {
    assertObjectId(driverId, 'driverId');
    trip.driver = new mongoose.Types.ObjectId(driverId);
  }

  // Apply scalar field updates
  if (rest.source          !== undefined) trip.source          = rest.source;
  if (rest.destination     !== undefined) trip.destination     = rest.destination;
  if (rest.cargoWeight     !== undefined) trip.cargoWeight     = rest.cargoWeight;
  if (rest.plannedDistance !== undefined) trip.plannedDistance = rest.plannedDistance;

  await trip.save();
  return trip;
}

/**
 * DELETE /api/trips/:id
 * Hard-deletes a trip.
 *
 * Business rules:
 *  - Only Draft or Cancelled trips may be deleted.
 *  - Active (Dispatched) or completed trips must be retained for audit.
 */
export async function deleteTrip(id: string) {
  assertObjectId(id, 'trip ID');

  const trip = await Trip.findById(id);
  if (!trip) throw new ApiError(404, 'Trip not found');

  const deletableStatuses: TripStatus[] = [TripStatus.DRAFT, TripStatus.CANCELLED];
  if (!deletableStatuses.includes(trip.status)) {
    throw new ApiError(
      409,
      `Cannot delete a trip with status "${trip.status}". Only Draft or Cancelled trips can be deleted.`,
    );
  }

  await Trip.deleteOne({ _id: id });
  return { tripNumber: trip.tripNumber };
}
