export const vehicleData = [
  {
    id: 1,
    vehicleNumber: 'VT-204',
    type: 'Van',
    driver: 'Amina Yusuf',
    status: 'Active',
    fuelLevel: 82,
    lastService: '2026-06-12',
    region: 'North Zone',
  },
  {
    id: 2,
    vehicleNumber: 'TR-118',
    type: 'Truck',
    driver: 'Daniel Kim',
    status: 'Available',
    fuelLevel: 64,
    lastService: '2026-06-08',
    region: 'Central Zone',
  },
  {
    id: 3,
    vehicleNumber: 'BUS-305',
    type: 'Bus',
    driver: 'Sara Mendez',
    status: 'Maintenance',
    fuelLevel: 28,
    lastService: '2026-06-03',
    region: 'West Zone',
  },
  {
    id: 4,
    vehicleNumber: 'VT-412',
    type: 'Van',
    driver: 'Noah Brooks',
    status: 'Active',
    fuelLevel: 76,
    lastService: '2026-06-15',
    region: 'East Zone',
  },
  {
    id: 5,
    vehicleNumber: 'TR-227',
    type: 'Truck',
    driver: 'Lina Patel',
    status: 'Available',
    fuelLevel: 91,
    lastService: '2026-06-10',
    region: 'South Zone',
  },
  {
    id: 6,
    vehicleNumber: 'BUS-189',
    type: 'Bus',
    driver: 'Mason Reed',
    status: 'Active',
    fuelLevel: 58,
    lastService: '2026-06-11',
    region: 'North Zone',
  },
  {
    id: 7,
    vehicleNumber: 'VT-503',
    type: 'Van',
    driver: 'Hannah Scott',
    status: 'Maintenance',
    fuelLevel: 33,
    lastService: '2026-05-29',
    region: 'Central Zone',
  },
  {
    id: 8,
    vehicleNumber: 'TR-344',
    type: 'Truck',
    driver: 'Omar Hassan',
    status: 'Available',
    fuelLevel: 71,
    lastService: '2026-06-07',
    region: 'West Zone',
  },
  {
    id: 9,
    vehicleNumber: 'BUS-612',
    type: 'Bus',
    driver: 'Jules Carter',
    status: 'Active',
    fuelLevel: 88,
    lastService: '2026-06-14',
    region: 'East Zone',
  },
  {
    id: 10,
    vehicleNumber: 'VT-701',
    type: 'Van',
    driver: 'Priya Singh',
    status: 'Maintenance',
    fuelLevel: 22,
    lastService: '2026-06-01',
    region: 'South Zone',
  },
];

export const vehicleStatuses = ['All', 'Active', 'Maintenance', 'Available'];
export const vehicleTypes = ['All', 'Van', 'Truck', 'Bus'];
